# Generated by Django 2.0.6 on 2018-11-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimensionX', models.IntegerField(default=0)),
                ('dimensionY', models.IntegerField(default=0)),
                ('insights', models.TextField(default='[]')),
                ('url', models.CharField(max_length=200)),
            ],
        ),
    ]
